stages:
  - ci
  - deploy
ci:
  stage: ci
  script:
    - ./scripts/ci/ci.sh
  artifacts:
    paths:
      - coverage/

production:
  stage: deploy
  script:
    - touch .env
    - export DEPLOY_TARGET=production

    - echo "REDISCLOUD_URL=$PRODUCTION_REDIS_URL" >> .env
    - echo "REDISCLOUD_PORT=$PRODUCTION_REDIS_PORT" >> .env
    - echo "REDISCLOUD_PASSWORD=$PRODUCTION_REDIS_PASSWORD" >> .env

    - echo "AWS_ACCESS_KEY_ID=$PRODUCTION_AWS_KEY_ID" >> .env
    - echo "AWS_SECRET_ACCESS_KEY=$PRODUCTION_AWS_SECRET_KEY" >> .env
    - echo "STRIPE_CLIENT_ID=$PRODUCTION_STRIPE_CLIENT_ID" >> .env

    - ./scripts/ci/deploy.sh
  only:
   - master

# pages:
#   stage: deploy
#   script:
#     - rm -rf public/coverage/
#     - mv coverage/ public/
#   only:
#   - develop
#   - master
#   artifacts:
#     paths:
#       - public
#     expire_in: 30 days
