version: "2"
services:
  test-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    ports:
      - 4310:4310
      - 4311:4311
    tty: false
    volumes:
      - .:/web
    env_file:
      - .env
