version: "2"
services:
  # for development only
  # assets are compiled and stored on s3 for production
  server:
    # image: nullvoxpopuli/ember-cli
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "ember server --port 4300 --live-reload-port 59153"
    ports:
      - 4300:4300
      - 59153:59153
      - 7357:7357

    volumes:
      # Mount the app code inside the container's `/usr/src/app` directory:
      # - .:/usr/src/app
      #- .:/web
      - ./app:/web/app
      - ./config:/web/config
      - ./mirage:/web/mirage
      - ./public:/web/public
      - ./scripts:/web/scripts
      - ./tests:/web/tests
      - ./vendor:/web/vendor

      - ./.bowerrc:/web/.bowerrc
      - ./.ember-cli:/web/.ember-cli
      - ./.eslintignore:/web/.eslintignore
      - ./.eslintrc.js:/web/.eslintrc.js
      - ./bower.json:/web/bower.json
      - ./ember-cli-build.js:/web/ember-cli-build.js
      - ./package.json:/web/package.json
      - ./testem.js:/web/testem.js
      - ./yarn.lock:/web/yarn.lock
      - ./tsconfig.json:/web/tsconfig.json

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as debugging, etc:
    # stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    # tty: true

    # ember deploy production / ember deploy staging
    # change / create this to deploy
    env_file:
      - .env
    environment:
      - STRIPE_CLIENT_ID=ca_4oEqCCUzDfLTBqXsFbXyklhVUP8XdOfO
