version: "2"
services:
  # for development only
  # assets are compiled and stored on s3 for production
  server:
    # image: nullvoxpopuli/ember-cli
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "ember server --port 4300 --live-reload-port 59153"
    ports:
      - 4300:4300
      - 59153:59153
      - 7357:7357

    volumes:
      # Mount the app code inside the container's `/usr/src/app` directory:
      # - .:/usr/src/app
      #- .:/myapp
      - ./app:/myapp/app
      - ./coverage:/myapp/coverage
      - ./config:/myapp/config
      - ./mirage:/myapp/mirage
      - ./public:/myapp/public
      - ./scripts:/myapp/scripts
      - ./tests:/myapp/tests
      - ./vendor:/myapp/vendor

      - ./.bowerrc:/myapp/.bowerrc
      - ./.ember-cli:/myapp/.ember-cli
      - ./.eslintignore:/myapp/.eslintignore
      - ./.eslintrc.js:/myapp/.eslintrc.js
      - ./bower.json:/myapp/bower.json
      - ./ember-cli-build.js:/myapp/ember-cli-build.js
      - ./package.json:/myapp/package.json
      - ./testem.js:/myapp/testem.js
      - ./yarn.lock:/myapp/yarn.lock
      - ./tsconfig.json:/myapp/tsconfig.json

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as debugging, etc:
    # stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    # tty: true

    # ember deploy production / ember deploy staging
    # change / create this to deploy
    env_file:
      - .env
    environment:
      - STRIPE_CLIENT_ID=ca_4oEqCCUzDfLTBqXsFbXyklhVUP8XdOfO
